config/routes.rb
MyFi::Application.routes.draw do
  resources :transactions
  resources :incomes, :except => [:index]
  resources :outgoings, :except => [:index]
  resources :financial_breakdown, :only => [:index]
  resource :session, :only => [:new, :create, :destroy]
  resource :users
  resource :financial_dashboard, :only => [:index]

  match 'logout', :controller => 'sessions', :action => 'destroy'
  match 'login', :controller => 'sessions', :action => 'new'
  match 'dashboard', :controller => 'financial_dashboard', :action => 'index'
  root :to => 'financial_dashboard#index'
end

app/controllers/financial_breakdown_controller.rb
class FinancialBreakdownController < ApplicationController
  before_filter :monthly_totals
  def index
    @income_breakdown = current_user.income_entries.monthly_breakdown
    @outgoing_breakdown = current_user.outgoing_entries.monthly_breakdown
  end
end

app/views/financial_breakdown/index.html.erb
<h2>Monthly breakdown</h2>
<div class="span18">
  <div class="row span5">
    <h2>Income</h2>
    <ul id="income-breakdown">
      <% @income_breakdown.each do |income| %>
        <li class="income">
          <%= income.type %> - <%= income.amount.to_f %> - <%= income.created_at %>
          <span><%= link_to "x", income_path(income), :method => :delete %></span>
          <span><%= link_to "edit", edit_income_path(income) %></span>
        </li>
        <%end %>
      </ul>
      <hr />
      <span>Total: <%= @monthly_income %></span>
    </div>
    <div class="row span5">
      <h2>Outgoings</h2>
      <ul id="outgoing-breakdown">
        <% @outgoing_breakdown.each do |outgoing| %>
          <li class="outgoing">
            <%= outgoing.type %> - <%= outgoing.amount.to_f %> - <%= outgoing.created_at %>
            <span><%= link_to "x", outgoing_path(outgoing), :method => :delete %></span>
            <span><%= link_to "edit", edit_outgoing_path(outgoing) %></span>
          </li>
        <%end %>
      </ul>
      <hr />
      <span>Total: <%= @monthly_outgoing %></span>
    </div>
  </div>
  <div class="row span5">
    <span>Total Monthly: <%= @monthly_total %></span>
  </div>
</div>