config/routes.rb
MyFi::Application.routes.draw do
  resources :transactions
  resources :incomes, :except => [:index]
  resources :outgoings, :except => [:index]
  resources :financial_breakdown, :only => [:index]
  resource :session, :only => [:new, :create, :destroy]
  resource :users
  resource :financial_dashboard, :only => [:index]

  match 'logout', :controller => 'sessions', :action => 'destroy'
  match 'login', :controller => 'sessions', :action => 'new'
  match 'dashboard', :controller => 'financial_dashboard', :action => 'index'
  root :to => 'financial_dashboard#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>MyFi</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield :js %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <span class="login-status">
      Signed in as: <%= current_user.email %>
    </span>
  <% end %>
  <nav class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <ul class="nav">
          <li> <%= link_to "Dashboard", dashboard_path %></li>
          <li> <%= link_to "New transaction", new_transaction_path %></li>
          <li> <%= link_to "Financial Breakdown", financial_breakdown_index_path %></li>
        <% if current_user %>
          <li><%= link_to "Logout", session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_session_path %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <% flash.each do |key, value| %>
      <div class="alert alert-block alert-<%= key == :notice ? "success" : key %> fadeout" data-dismiss="alert">
        <a class="close">×</a>
        <h4 class="alert-heading"><%= key.capitalize %>:</h4>
        <%= value %>
      </div>
  <% end %>
  <div class="container-fluid">
    <%= yield %>
  </div>

</body>
</html>